language: node_js
node_js:
  - '16.14.2'

services:
  - docker

before_script:
  - docker pull mysql:latest
  - docker pull node:16.14.2

script:
  - docker run -d -p 3306:3306 mysql:latest
  - npm install
  - npm run build
  - npm run start:prod
