language: node_js
node_js:
  - '16.14.2'

services:
  - docker

before_script:
  - docker pull mysql:latest

script:
  - docker run -d -p 3307:3307 mysql
  - npm install
  - npm run build
  - npm run start:prod
