env:
  global:
    - BUILD_TIMEOUT=300 # Define um limite de 10 minutos para todo o build
language: node_js
node_js:
  - '16.14.2'

services:
  - docker

before_script:
  - docker pull mysql:latest
  - docker pull node:16.14.2

script:
  - docker build -t mysql:latest -f Dockerfile.mysql .
  - docker build -t server:latest -f Dockerfile.server .
  - docker run -d -p 3306:3306 mysql:latest
  - npm install
  - npm run build
  - npm run start:prod

after_script:
